CREATE TABLE CLIENT
(
    CLIENT_ID    BIGINT NOT NULL PRIMARY KEY,
    FULL_NAME    VARCHAR(70),
    PHONE_NUMBER VARCHAR(13),
    EMAIL        VARCHAR(40),
    PASSPORT_ID  VARCHAR(6)
);

CREATE TABLE CREDIT
(
    CREDIT_ID     BIGINT NOT NULL PRIMARY KEY,
    `LIMIT`       BIGINT,
    INTEREST_RATE DOUBLE,
    NAME          VARCHAR(50)
);

CREATE TABLE CREDIT_OFFER
(
    CREDIT_OFFER_ID BIGINT NOT NULL PRIMARY KEY,
    CLIENT_ID       BIGINT,
    CREDIT_ID       BIGINT,
    BANK_ID         BIGINT,
    AMOUNT          BIGINT,
    MONTH_COUNT     BIGINT
);
